# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-client
  namespace: bill-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-client
  template:
    metadata:
      labels:
        app: ingress-client
    spec:
      containers:
      - name: ingress-client-container
        image: BillTestContainerRegistry.azurecr.io/ingress-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      